name: Make PDF

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get install -y --no-install-recommends \
          python3-docutils \
          texlive-xetex latexmk \
          texlive-fonts-recommended \
          fonts-linuxlibertine \
          fonts-dejavu-core
    - name: make
      run: |
        make RST2XETEX=rst2xetex
    - uses: actions/upload-artifact@v4
      with:
        name: constitution
        path: constitution.pdf

  release:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: constitution
    - name: Github release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          constitution.pdf
