name: Make PDF

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install -y --no-install-recommends \
          python3-docutils \
          texlive-xetex latexmk \
          texlive-fonts-recommended \
          fonts-linuxlibertine \
          fonts-dejavu-core
    - name: make
      run: |
        make RST2XETEX=rst2xetex
    - uses: actions/upload-artifact@v2
      with:
        name: constitution
        path: constitution.pdf

  release:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: constitution
    - uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: constitution.pdf
        asset_name: constitution.pdf
        asset_content_type: application/pdf
